### ISSUE TITLE
Readme out of date

### ISSUE THREAD

**Issue by andrewchambers** [LewisGaul/zig-nestedtext#23]
It seems like the spec around inline-dicts and inline-lists has changed and now matches what this library does, making the notes in the readme less necessary... I may be mistaken though.

And just as an FYI, I did a nested text implementation in janet for fun: https://github.com/andrewchambers/janet-nested-text/blob/master/nested-text.janet  , so this library was really handy as a reference.

**Comment by LewisGaul** [comment]
This implementation implements v2.0 of the spec, as the readme says - the notes apply to that version (but could be updated to acknowledge v3.0).

v3.0 of the spec improves the situation by removing the weird trailing comma treatment, but introduces a new slightly odd case where whitespace is ignored in inline containers except one case: distinguishing an empty list from a list containing a single empty string (`[]` and `[ ]`). I'm not a massive fan of this, so I'm not very motivated to update to 3.0. This means my implementation remains a strict subset where I disallow representing empty values in flow style, and the readme notes are still relevant.

**Comment by andrewchambers** [comment]
>whitespace is ignored in inline containers except one case: distinguishing an empty list from a list containing a single empty string ([] and [ ])

I interpreted it as whitespace is trimmed after parsing, the end result is the same, but it sounds like less of a gross edge case when described this way. I think the main reason for this is so that dictionaries can look like `{ a : b }` instead of `{a:b}`, which seemed fairly well justified. Tbh, I wouldn't worry too much as inline dictionaries and lists only really need to be used for empty lists and dictionaries anyway.

One thing that confused me a lot was treating a single \r as a newline, but to me interop trumps many of those nits.

**Comment by LewisGaul** [comment]
> I think the main reason for this is so that dictionaries can look like `{ a : b }` instead of `{a:b}`

Oh I have no problem with the trimming of whitespace, this is fine. What I don't like is that `[]` and `[ ]` should be treated differently, considering `[a]` and `[a ]` (or any other variant involving whitespace) are treated the same.

Out of interest, what's your feeling on how necessary it is to allow representing empty strings in flow style? E.g. do you consider there to be much need to support things like `[1, , 2, ]` to mean `["1", "", "2", ""]`? My stance is that this is just hard to read and the full list form should be used instead.

**Comment by andrewchambers** [comment]
> Oh I have no problem with the trimming of whitespace, this is fine. What I don't like is that [] and [ ] should be treated differently, considering [a] and [a ] (or any other variant involving whitespace) are treated the same.

Ah I see.

> what's your feeling on how necessary it is to allow representing empty strings in flow style?

I don't really have a problem with it, but wasn't planning on using flow style much at all to begin with.
